project:
  type: website

website:
  title: "Roy Meijer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About/about.qmd
        text: About
      - href: Research/research.qmd
        text: Research
      - href: Teaching/teaching.qmd
        text: Teaching

    right:
      - icon: github
        href: https://github.com/MeijerRoy
      - icon: linkedin
        href: https://www.linkedin.com/in/roy-meijer

    google-analytics: "G-S4Z8G29JNE"

format:
  html:
    theme:
      dark: darkly
      light: flatly

editor: visual

execute:
  freeze: auto
