project:
  type: website

website:
  title: "Roy Meijer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About/about.qmd
        text: About
      - href: Research/research.qmd
        text: Research
      - href: Teaching/teaching.qmd
        text: Teaching

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/roy-meijer
      - icon: person-circle
        href: https://roa.nl/p70078533
      - icon: file-earmark-text-fill
        href: https://cris.maastrichtuniversity.nl/en/persons/roy-meijer
      - icon: github
        href: https://github.com/MeijerRoy
        # Find all available icons here: https://icons.getbootstrap.com/

  google-analytics:
    tracking-id: "G-S4Z8G29JNE"

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
