project:
  type: website

website:
  title: "Roy Meijer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About/about.qmd
        text: About

    right:
      - icon: github
        href: https://github.com/MeijerRoy
      - icon: linkedin
        href: https://www.linkedin.com/in/roy-meijer

format:
  html:
    theme:
      dark: darkly
      light: flatly

editor: visual

execute:
  freeze: auto
